# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('log', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('wid_city', models.IntegerField(unique=True)),
                ('zip_code', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pressure', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cloudiness', models.CharField(max_length=250)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wind_speed', models.DecimalField(decimal_places=4, max_digits=8)),
                ('wind_deg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('temp_min', models.DecimalField(decimal_places=4, max_digits=8)),
                ('temp_max', models.DecimalField(decimal_places=4, max_digits=8)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapp.City')),
            ],
        ),
    ]
